In [1]:
import os
import pathlib
import datetime
import IPython
import IPython.display
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf

mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False

np.set_printoptions(precision=4)

In [3]:
#!pip install yfinance
import yfinance as yf

     |████████████████████████████████| 5.5MB 8.2MB/s 
  Created wheel for yfinance: filename=yfinance-0.1.55-py2.py3-none-any.whl size=22618 sha256=66820470b2244444fde2dc88d34594fd7f7e4941d288dbaaa7fd63884b060e79
  Stored in directory: /root/.cache/pip/wheels/04/98/cc/2702a4242d60bdc14f48b4557c427ded1fe92aedf257d4565c
Successfully built yfinance
  Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6


In [30]:
data = yf.download("^GSPC",interval='1d',auto_adjust=True)

[*********************100%***********************]  1 of 1 completed


In [36]:

df= data.drop(columns=['Volume']).apply(np.log2)

In [37]:
date_time=pd.to_datetime(df.index,infer_datetime_format=True)
date_time

DatetimeIndex(['1927-12-30', '1928-01-03', '1928-01-04', '1928-01-05',
               '1928-01-06', '1928-01-09', '1928-01-10', '1928-01-11',
               '1928-01-12', '1928-01-13',
               ...
               '2020-11-10', '2020-11-11', '2020-11-12', '2020-11-13',
               '2020-11-16', '2020-11-17', '2020-11-18', '2020-11-19',
               '2020-11-20', '2020-11-23'],
              dtype='datetime64[ns]', name='Date', length=23336, freq=None)

In [55]:
date_time + pd.Timedelta( np.random.randint(8*60*60*1E9,size=date_time.size))
#df = df[df['date_time'].apply(lambda x: x.weekday() not in [5,6])]
#pd.timedelta_range(start='0 D',end='1 D', periods=4 ,closed='left')

ValueError: ignored

In [60]:
date_time.values + np.random.randint(8*60*60*1E9,size=(date_time.size,2))

ValueError: ignored

In [162]:
date_time.size
a=np.arange(0,date_time.size*4,4)
b=np.random.randint(1,3,size=(date_time.size))
c = 3 - b
b += a
c += a
d = a +3
a,b,c,d


(array([    0,     4,     8, ..., 93332, 93336, 93340]),
 array([    1,     6,     9, ..., 93333, 93338, 93342]),
 array([    2,     5,    10, ..., 93334, 93337, 93341]),
 array([    3,     7,    11, ..., 93335, 93339, 93343]))

In [163]:
df['Open']
#pd.Series(df['Open'],index=a)
df['io']=a
df['ih']=b
df['il']=c
df['ic']=d
df[['io','Open']].values
kk=pd.DataFrame(data=df['Open'].values,index=df['io'].values,  columns=['val'] )
kk=kk.append(pd.DataFrame(data=df['High'].values,index=df['ih'].values,  columns=['val'] ),sort=True)
kk=kk.append(pd.DataFrame(data=df['Low'].values,index=df['il'].values, columns=['val'] ),sort=True)
kk=kk.append(pd.DataFrame(data=df['Close'].values,index=df['ic'].values, columns=['val'] ),sort=True)

In [164]:
df
kk

val
0       4.142413
4       4.150560
8       4.147307
12      4.133399
16      4.142413
...          ...
93327  11.817595
93331  11.800815
93335  11.806497
93339  11.796664
93343  11.804772

[93344 rows x 1 columns]

In [171]:
kk.sort_index(inplace=True)
(kk*0).sort_index()
kk

val
0       4.142413
1       4.142413
2       4.142413
3       4.142413
4       4.150560
...          ...
93339  11.796664
93340  11.800423
93341  11.794729
93342  11.809692
93343  11.804772

[93344 rows x 1 columns]